### PR TITLE
Third commit created UserController

### PR DESCRIPTION
**Pull request by AnidaMalkic**
hi, I have created UserController, modified a user model.

### CODE REVIEW

**Review by specialtas — APPROVED** [review]
Thank you for your hard work. I will approve this edit and merge.

**Review by CleeMe — COMMENTED** [review]
You were the first for the project!!  Great job!

**Review by CleeMe — COMMENTED** [review]
I am not sure if this still needs reviewed based on Tracy's comment but will try it.  Don't forget to merge!

**Review by CleeMe — COMMENTED** [review]
I think I did th eprevious reviews incorrectly. I didn't have a checkbox clicked. I am sorry I am learning.

**Pull request merged**
